### ISSUE TITLE
Tests for other Operating Systems

### ISSUE THREAD

**Issue by CodeUnstable** [Cylvre-Language/Cylvre#5]
The compiler still is not complete, but tests need to be run for macOS and Linux to see whether the instructions provided in the [README](https://github.com/Cylvre-Language/Cylvre/blob/main/README.md) work for them. Check [Features.md](https://github.com/Cylvre-Language/Cylvre/blob/main/Features.md) to see what can compile and run successfully.

**Comment by SivAxis** [comment]
If you have tested the compiler for any OS and it was successful, comment here saying:
______ OS test successful.
